apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: me-pvc
  namespace: motioneye
  labels:
    app: motioneye
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: microk8s-hostpath
