apiVersion: v1
kind: Service
metadata:
  name: motioneye-service
  namespace: motioneye
spec:
  selector:
    app: motioneye
  ports:
    - protocol: TCP
      port: 8765
      targetPort: 8765
      nodePort: 32765
  type: NodePort
