apiVersion: v1
kind: Pod
metadata:
  name: pvc-inspector
  namespace: motioneye
spec:
  containers:
  - name: inspector
    image: alpine
    command: ["/bin/sh", "-c", "sleep 3600"]
    volumeMounts:
    - mountPath: /mnt/k8s-pvcs/me
      name: inspect-volume
  volumes:
  - name: inspect-volume
    persistentVolumeClaim:
      claimName: me-pvc
  restartPolicy: Never
